remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: Artemis (ARX)
description: Artemis Home Page
show_downloads: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      custom_css: assets/css/custom.css
